//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BhavnasUI.data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BhavanasERPEntities : DbContext
    {
        public BhavanasERPEntities()
            : base("name=BhavanasERPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAddtocart> tblAddtocarts { get; set; }
        public virtual DbSet<tblcarrer> tblcarrers { get; set; }
        public virtual DbSet<tblCategory> tblCategories { get; set; }
        public virtual DbSet<tblCustomer> tblCustomers { get; set; }
        public virtual DbSet<tblCustomerInvoice> tblCustomerInvoices { get; set; }
        public virtual DbSet<tblCustomerInvoiceDetail> tblCustomerInvoiceDetails { get; set; }
        public virtual DbSet<tblCustomerOrder> tblCustomerOrders { get; set; }
        public virtual DbSet<tblCustomerOrderDetail> tblCustomerOrderDetails { get; set; }
        public virtual DbSet<tblFeedback> tblFeedbacks { get; set; }
        public virtual DbSet<tblFranchise> tblFranchises { get; set; }
        public virtual DbSet<tblFranchiseAccount> tblFranchiseAccounts { get; set; }
        public virtual DbSet<tblFranchiseInvoice> tblFranchiseInvoices { get; set; }
        public virtual DbSet<tblFranchiseInvoiceDetail> tblFranchiseInvoiceDetails { get; set; }
        public virtual DbSet<tblFranchiseOrder> tblFranchiseOrders { get; set; }
        public virtual DbSet<tblFranchiseOrderDetail> tblFranchiseOrderDetails { get; set; }
        public virtual DbSet<tblProduct> tblProducts { get; set; }
    }
}
