//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BhavnasUI.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAddtocart
    {
        public int Id { get; set; }
        public string CustomerIP { get; set; }
        public Nullable<long> ProductID { get; set; }
        public Nullable<long> Quantity { get; set; }
        public string Size { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Shipping { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> UpdationDate { get; set; }
        public Nullable<decimal> GrandTotal { get; set; }
    }
}
