//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BhavnasUI.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblcarrer
    {
        public int id { get; set; }
        public string Name { get; set; }
        public Nullable<long> MobileNo { get; set; }
        public Nullable<System.DateTime> Dateofbirth { get; set; }
        public string ResumeFile { get; set; }
        public string Position { get; set; }
        public Nullable<decimal> ExpectatedSalary { get; set; }
        public string EmpAddress { get; set; }
        public Nullable<System.DateTime> creationdate { get; set; }
    }
}
