//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BhavnasUI.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFranchiseInvoice
    {
        public int Id { get; set; }
        public int FranchiseId { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> SGST { get; set; }
        public Nullable<decimal> CGST { get; set; }
        public Nullable<decimal> IGST { get; set; }
        public Nullable<decimal> PayableAmount { get; set; }
        public string PaymentMode { get; set; }
        public string DeliveryState { get; set; }
        public string DeliveryBy { get; set; }
        public string DeliveryPerson { get; set; }
        public string Deliverycontact { get; set; }
    }
}
